### ISSUE TITLE
Error when use API in Angular 5 + typescript project

### ISSUE THREAD

**Issue by tosun-si** [jiaweihli/monapt#21]
Hi.
I want to use this API in a Angular 5 + typescript project (and webpack), but i have an error in the compilation.

ERROR in node_modules/monapt/dist/src/future/future.d.ts(1,23): error TS2688: Cannot find type definition file for 'when'.

Thanks for your help.

**Comment by jiaweihli** [comment]
This was fixed in https://github.com/jiaweihli/monapt/commit/7c0814c3, and was released in 2.0.0 - give that a shot!  Re-open this if you're still seeing issues.
